# Базовые параметры настройки конфигурации проекта
dbname: study # В классе менять не надо
user: myuser # Замените на свой логин от БД в классе
password: Fgghsc#Postgres # Замените на свой пароль от БД в классе
host: localhost # Замените на 192.168.0.48 в классе
dbtableprefix: "public."  # Замените на свой логин от БД